apiVersion: v1
kind: ServiceAccount
metadata:
  name: twitterplay

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: twitterplay
  name: twitterplay
  # namespace: tp-namespace
spec:
  selector:
    matchLabels:
      app: twitterplay
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: twitterplay
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - command: [ "sh", "-c", "NODE_ENV='kube' PORT=9098 WINSTON_PORT=9095 NODE_HOST='localhost' MONGO_CONN_URL='mongodb://tp-mongodb-0.tp-mongodb-svc:27017/twitterplay' PELIAS_HOST='tp-pelias-api-svc' RABBIT_MQ_CONN_URL='guest:guest@tp-rabbitmq-svc:5678' node --no-warnings --no-deprecation --max_old_space_size=8000 server.js" ]
        image: aswin1906/twitterplay:1.0
        name: twitterplay
        ports:
        - containerPort: 9098
        resources: {}
        volumeMounts:
        - mountPath: /scripts
          name: twitterplay-claim
      restartPolicy: Always
      volumes:
      - name: twitterplay-claim
        persistentVolumeClaim:
          claimName: twitterplay-claim
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: twitterplay-claim
  name: twitterplay-claim
  # namespace: tp-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: twitterplay
  name: twitterplay
  annotations:
    'consul.hashicorp.com/service-sync': 'true'
  # namespace: tp-namespace
spec:
  # type: LoadBalancer
  ports:
  - name: "9098"
    protocol: TCP
    port: 9098
    targetPort: 9098
    # nodePort: 30020
  selector:
    app: twitterplay
status:
  loadBalancer: {}
