apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tp-mongodb
  namespace: tp-mongo-namespace
  labels:
    app: tp-mongodb
spec:
  selector:
    matchLabels:
      app: tp-mongodb
  serviceName: "tp-mongodb-svc"
  replicas: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tp-mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - command:
        - mongod
        - --bind_ip_all
        - --replSet
        - rs0
        image: aswin1906/tp-mongodb4.0:1.0
        name: tp-mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: tp-mongodb-claim
  volumeClaimTemplates:
    - metadata:
        name: tp-mongodb-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: tp-mongodb-0-svc
  namespace: tp-mongo-namespace
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: tp-mongodb-0
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: tp-mongodb-1-svc
  namespace: tp-mongo-namespace
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: tp-mongodb-1
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
