apiVersion: v1
kind: Service
metadata:
  labels:
    name: tp-mongodb-svc
  name: tp-mongodb-svc
  annotations:
    'consul.hashicorp.com/service-sync': 'true'
  # namespace: tp-mongo-namespace
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      name: tp-mongodb
  selector:
    app: tp-mongodb
